let prod=[
    {
        id:1,
        img:"https://images.asos-media.com/products/calvin-klein-3-pack-cotton-stretch-trunks-in-black/200940987-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein 3 pack cotton stretch trunks in black",
        brand:"Calvin Klein",
        type:"underwear",
        price:40.00,
    },
    {
        id:2,
        img:"https://images.asos-media.com/products/calvin-klein-jeans-big-tall-two-tone-monogram-logo-t-shirt-in-black/201571277-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein Jeans Big & Tall two tone monogram logo t-shirt in black",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:35.00,
        
    },
    {
        id:3,
        img:"https://images.asos-media.com/products/calvin-klein-jeans-big-tall-monogram-logo-t-shirt-in-light-blue/201568567-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein Jeans Big & Tall monogram logo t-shirt in light blue",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:4,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-t-shirt-with-neck-branding-detail-in-cream/201382920-1-cream?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS t-shirt with neck branding detail in cream",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:5,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-t-shirt-in-teal/201382984-1-teal?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo t-shirt in teal",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:6,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-sweatshirt-in-lilac/201383207-1-lilac?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo sweatshirt in lilac",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:85.00,
    },
    {
        id:7,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-hoodie-in-teal/201383188-1-teal?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo hoodie in teal",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:90.00,
    },
    {
        id:8,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-t-shirt-in-lilac/201383029-1-lilac?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo t-shirt in lilac",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:9,
        img:"https://images.asos-media.com/products/tommy-jeans-big-tall-timeless-circle-logo-t-shirt-in-black/201891883-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans Big & Tall timeless circle logo t-shirt in black",
        brand:"Tommy",
        type:"T-shirts",
        price:42.00,
    },
    {
        id:10,
        img:"https://images.asos-media.com/products/tommy-jeans-big-tall-collegiate-tie-dye-logo-t-shirt-classic-fit-in-navy/201480783-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans Big & Tall collegiate tie dye logo t-shirt classic fit in navy",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:11,
        img:"https://images.asos-media.com/products/tommy-jeans-flag-tie-dye-back-print-t-shirt-classic-fit-in-black/201477724-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans flag tie dye back print t-shirt classic fit in black",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:12,
        img:"https://images.asos-media.com/products/tommy-jeans-flag-tie-dye-back-print-t-shirt-classic-fit-in-white/201478807-1-white?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans flag tie dye back print t-shirt classic fit in black",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:13,
        img:"https://images.asos-media.com/products/tommy-hilfiger-gingham-print-short-sleeve-shirt-in-pale-yellow-white/201146588-1-lumenflashwhite?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger gingham print short sleeve shirt in pale yellow/white",
        brand:"Tommy",
        type:"Shirt",
        price:75.00,
    },
    {
        id:14,
        img:"https://images.asos-media.com/products/tommy-hilfiger-lightweight-twill-overshirt-in-navy/201456787-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger lightweight twill overshirt in navy",
        brand:"Tommy",
        type:"Shirt",
        price:85.00,
    },
    {
        id:15,
        img:"https://images.asos-media.com/products/tommy-hilfiger-big-tall-flag-logo-stretch-poplin-shirt-in-white/200737322-1-brightwhite?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger Big & Tall flag logo stretch poplin shirt in white",
        brand:"Tommy",
        type:"Shirt",
        price:85.00,
    },
    {
        id:16,
        img:"https://images.asos-media.com/products/tommy-jeans-archive-colourblock-tencel-short-sleeve-camp-shirt-boxy-fit-in-navy/201891234-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans archive colourblock tencel short sleeve camp shirt boxy fit in navy",
        brand:"Tommy",
        type:"Shirt",
        price:63.00,
    },
    // {
    //     id:,
    //     img:,
    //     title:,
    //     brand:,
    //     type:,
    //     price:,
    // },
    // {
    //     id:,
    //     img:,
    //     title:,
    //     brand:,
    //     type:,
    //     price:,
    // },
    // {
    //     id:,
    //     img:,
    //     title:,
    //     brand:,
    //     type:,
    //     price:,
    // },
    // {
    //     id:,
    //     img:,
    //     title:,
    //     brand:,
    //     type:,
    //     price:,
    // },
    // {
    //     id:,
    //     img:,
    //     title:,
    //     brand:,
    //     type:,
    //     price:,
    // },

]
