let prod=[
    {
        id:1,
        img:"https://images.asos-media.com/products/calvin-klein-3-pack-cotton-stretch-trunks-in-black/200940987-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein 3 pack cotton stretch trunks in black",
        brand:"Calvin Klein",
        type:"underwear",
        price:40.00,
    },
    {
        id:2,
        img:"https://images.asos-media.com/products/calvin-klein-jeans-big-tall-two-tone-monogram-logo-t-shirt-in-black/201571277-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein Jeans Big & Tall two tone monogram logo t-shirt in black",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:35.00,
        
    },
    {
        id:3,
        img:"https://images.asos-media.com/products/calvin-klein-jeans-big-tall-monogram-logo-t-shirt-in-light-blue/201568567-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein Jeans Big & Tall monogram logo t-shirt in light blue",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:4,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-t-shirt-with-neck-branding-detail-in-cream/201382920-1-cream?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS t-shirt with neck branding detail in cream",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:5,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-t-shirt-in-teal/201382984-1-teal?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo t-shirt in teal",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:6,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-sweatshirt-in-lilac/201383207-1-lilac?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo sweatshirt in lilac",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:85.00,
    },
    {
        id:7,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-hoodie-in-teal/201383188-1-teal?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo hoodie in teal",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:90.00,
    },
    {
        id:8,
        img:"https://images.asos-media.com/products/calvin-klein-exclusive-to-asos-centre-logo-t-shirt-in-lilac/201383029-1-lilac?$n_320w$&wid=317&fit=constrain",
        title:"Calvin Klein exclusive to ASOS centre logo t-shirt in lilac",
        brand:"Calvin Klein",
        type:"T-shirts",
        price:40.00,
    },
    {
        id:9,
        img:"https://images.asos-media.com/products/tommy-jeans-big-tall-timeless-circle-logo-t-shirt-in-black/201891883-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans Big & Tall timeless circle logo t-shirt in black",
        brand:"Tommy",
        type:"T-shirts",
        price:42.00,
    },
    {
        id:10,
        img:"https://images.asos-media.com/products/tommy-jeans-big-tall-collegiate-tie-dye-logo-t-shirt-classic-fit-in-navy/201480783-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans Big & Tall collegiate tie dye logo t-shirt classic fit in navy",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:11,
        img:"https://images.asos-media.com/products/tommy-jeans-flag-tie-dye-back-print-t-shirt-classic-fit-in-black/201477724-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans flag tie dye back print t-shirt classic fit in black",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:12,
        img:"https://images.asos-media.com/products/tommy-jeans-flag-tie-dye-back-print-t-shirt-classic-fit-in-white/201478807-1-white?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans flag tie dye back print t-shirt classic fit in black",
        brand:"Tommy",
        type:"T-shirts",
        price:35.00,
    },
    {
        id:13,
        img:"https://images.asos-media.com/products/tommy-hilfiger-gingham-print-short-sleeve-shirt-in-pale-yellow-white/201146588-1-lumenflashwhite?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger gingham print short sleeve shirt in pale yellow/white",
        brand:"Tommy",
        type:"Shirt",
        price:75.00,
    },
    {
        id:14,
        img:"https://images.asos-media.com/products/tommy-hilfiger-lightweight-twill-overshirt-in-navy/201456787-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger lightweight twill overshirt in navy",
        brand:"Tommy",
        type:"Shirt",
        price:85.00,
    },
    {
        id:15,
        img:"https://images.asos-media.com/products/tommy-hilfiger-big-tall-flag-logo-stretch-poplin-shirt-in-white/200737322-1-brightwhite?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Hilfiger Big & Tall flag logo stretch poplin shirt in white",
        brand:"Tommy",
        type:"Shirt",
        price:85.00,
    },
    {
        id:16,
        img:"https://images.asos-media.com/products/tommy-jeans-archive-colourblock-tencel-short-sleeve-camp-shirt-boxy-fit-in-navy/201891234-1-navy?$n_320w$&wid=317&fit=constrain",
        title:"Tommy Jeans archive colourblock tencel short sleeve camp shirt boxy fit in navy",
        brand:"Tommy",
        type:"Shirt",
        price:63.00,
    },
    {
        id:17,
        img:"https://images.asos-media.com/products/asos-design-camera-bag-with-bandana-print-in-black-and-white/201206631-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN camera bag with bandana print in black and white",
        brand:"ASOS DESIGN",
        type:"Camera bag",
        price:16.00,
    },
    {
        id:18,
        img:"https://images.asos-media.com/products/asos-design-5-panel-cap-in-black-fleece-with-branding/201145543-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN 5 panel cap in black fleece with branding",
        brand:"ASOS DESIGN",
        type:"Cap",
        price:12.00,
    },
    {
        id:19,
        img:"https://images.asos-media.com/products/asos-design-baseball-cap-with-nasa-badges-in-black/201071107-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN baseball cap with NASA badges in black",
        brand:"ASOS DESIGN",
        type:"Cap",
        price:12.00,
    },
    {
        id:20,
        img:"https://images.asos-media.com/products/asos-design-retro-round-sunglasses-in-yellow-with-vintage-green-lens/200376143-1-yellow?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN retro round sunglasses in yellow with vintage green lens",
        brand:"ASOS DESIGN",
        type:"Sunglasses",
        price:13.00,
    },
    {
        id:21,
        img:"https://images.asos-media.com/products/asos-design-mid-rectangle-sunglasses-in-green-with-tinted-lens/200293214-1-lightgreen?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN mid rectangle sunglasses in yellow with tinted lens",
        brand:"ASOS DESIGN",
        type:"Jewelery",
        price:13.00,
    },
    {
        id:22,
        img:"https://images.asos-media.com/products/asos-design-band-ring-in-burnished-silver-tone/200559259-1-silver?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN band ring in burnished silver tone",
        brand:"ASOS DESIGN",
        type:"Jewelery",
        price:5.20,
    },
    {
        id:23,
        img:"https://images.asos-media.com/products/asos-design-square-signet-ring-with-embossing-in-gold-tone/201184182-1-gold?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN square signet ring with embossing in gold tone",
        brand:"ASOS DESIGN",
        type:"Jewelery",
        price:5.10,
    },
    {
        id:24,
        img:"https://images.asos-media.com/products/asos-design-colourful-beaded-neck-chain-with-snooker-ball-beads/201538288-1-multi?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN colourful beaded neck chain with snooker ball beads",
        brand:"ASOS DESIGN",
        type:"Jewelery",
        price:8.00,
    },
    {
        id:25,
        img:"https://images.asos-media.com/products/asos-actual-oversized-t-shirt-in-all-over-stripe-and-logo-prints-in-blue/201784544-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual oversized t-shirt in all over stripe and logo prints in blue",
        brand:"ASOS DESIGN",
        type:"T-shirt",
        price:18.00,
    },
    {
        id:26,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-relaxed-short-with-graphic-print-in-light-blue/201756073-1-lightblue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord relaxed short with graphic print in light blue",
        brand:"ASOS DESIGN",
        type:"Shirt",
        price:24.00,
    },
    {
        id:27,
        img:"https://images.asos-media.com/products/asos-design-knitted-vertical-stripe-tank-in-tan/201649069-1-tan?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN knitted vertical stripe tank in tan",
        brand:"ASOS DESIGN",
        type:"Shirt",
        price:16.25,
    },
    {
        id:28,
        img:"https://images.asos-media.com/products/asos-design-muscle-fit-pointelle-long-sleeve-jumper-in-black/201744108-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN muscle fit pointelle long sleeve jumper in black",
        brand:"ASOS DESIGN",
        type:"Shirt",
        price:34.00,
    },
    {
        id:29,
        img:"https://images.asos-media.com/groups/asos-design-ribbed-co-ord-cotton-in-icey-grey/72559-group-1?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN ribbed co-ord cotton in icey grey",
        brand:"ASOS DESIGN",
        type:"Shirt",
        price:28.00,
    },
    {
        id:30,
        img:"https://images.asos-media.com/products/asos-design-oversized-knitted-pointelle-jumper-in-black/201174228-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN oversized knitted pointelle jumper in black",
        brand:'ASOS DESIGN',
        type:"Shirt",
        price:34.00,
    },
    {
        id:31,
        img:"https://images.asos-media.com/products/asos-design-ribbed-co-ord-cotton-joggers-in-icey-grey/201278718-1-grey?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN ribbed co-ord cotton in icey grey",
        brand:"ASOS DESIGN",
        type:"JOGGERS",
        price:56.00,
    },
    {
        id:32,
        img:"https://images.asos-media.com/products/asos-design-co-ord-knitted-joggers-in-sage-green/201278682-1-green?$n_320w$&wid=317&fit=constrain",
        title:"ASOS DESIGN knitted co-ord in sage green",
        brand:"ASOS DESIGN",
        type:"Knitted",
        price:34.00,
    },
    {
        id:33,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-french-terry-reverse-sweatshirt-in-brown-with-back-logo/201207112-1-brown?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' french terry reverse sweatshirt in brown with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:65.00,
    },
    {
        id:34,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-collegiate-varsity-jacket-in-grey-with-back-logo/201217425-1-grey?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' collegiate varsity jacket in grey with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:140.00,
    },
    {
        id:35,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-waffle-t-shirt-in-carbon-black-with-back-logo/201207139-1-black?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' waffle t-shirt in carbon black with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:45.00,
    },
    {
        id:36,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-waffle-t-shirt-in-chalk-white-with-back-logo/201207158-1-white?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' waffle t-shirt in chalk white with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:45.00,
    },
    {
        id:37,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-t-shirt-in-brown-with-back-logo/201207055-1-brown?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' t-shirt in brown with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:33.00,
    },
    {
        id:38,
        img:"https://images.asos-media.com/groups/adidas-originals-tonal-textures-in-chalk-white-and-carbon-black/72231-group-1?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' in chalk white and carbon black",
        brand:"ADIDAS",
        type:"T-shirts",
        price:100.00,
    },
    {
        id:39,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-waffle-shorts-in-carbon-black/201217398-1-black?$n_320w$&wid=317&fit=constrain",
        title:"adidas Originals 'Tonal Textures' waffle t-shirt in chalk white with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:55.00,
    },
    {
        id:40,
        img:"https://images.asos-media.com/products/adidas-originals-tonal-textures-hoodie-in-off-white-with-back-logo/201207238-1-white?$n_320w$&wid=317&fit=constrain",
        title:"Adidas Originals 'Tonal Textures' hoodie in off white with back logo",
        brand:"ADIDAS",
        type:"T-shirts",
        price:70.00,
    },
    {
        id:41,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-oversized-t-shirt-with-front-graphic-print-in-light-blue/201755227-1-lightblue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord oversized t-shirt with front graphic print in light blue",
        brand:"ASOS DESIGN",
        type:"T-shirts",
        price:20.00,
    },
    {
        id:42,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-oversized-t-shirt-with-front-and-back-graphic-prints-in-teal/201809775-1-teal?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord oversized t-shirt with front and back graphic prints in teal",
        brand:"ASOS DESIGN",
        type:"T-shirts",
        price:18.00,
    },
    {
        id:43,
        img:"https://images.asos-media.com/products/asos-actual-oversized-sweatshirt-with-back-graphic-print-in-black/201679363-1-black?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual oversized sweatshirt with back graphic print in black",
        brand:"ASOS DESIGN",
        type:"sweatshirts",
        price:32.00,
    },
    {
        id:44,
        img:"https://images.asos-media.com/products/asos-actual-relaxed-t-shirt-with-front-graphic-print-in-white/201755983-1-white?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual relaxed t-shirt with front graphic print in white",
        brand:"ASOS DESIGN",
        type:"T-shirts",
        price:16.00,
    },
    {
        id:45,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-oversized-hoodie-with-large-back-graphic-embroidery-in-blue/201820048-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord oversized hoodie with large back graphic embroidery in blue",
        brand:"ASOS DESIGN",
        type:"Hoodie",
        price:36.00,
    },
    {
        id:46,
        img:"https://images.asos-media.com/products/asos-actual-oversized-t-shirt-in-all-over-stripe-and-logo-prints-in-blue/201784544-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual oversized t-shirt in all over stripe and logo prints in blue",
        brand:"ASOS DESIGN",
        type:"T-shirts",
        price:18.00,
    },
    {
        id:47,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-relaxed-jogger-with-leg-embroidery-in-blue/201820037-1-blue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord relaxed jogger with leg embroidery in blue",
        brand:"ASOS DESIGN",
        type:"Jogger",
        price:28.00,
    },
    {
        id:48,
        img:"https://images.asos-media.com/products/asos-actual-co-ord-relaxed-short-with-graphic-print-in-light-blue/201756073-1-lightblue?$n_320w$&wid=317&fit=constrain",
        title:"ASOS Actual co-ord relaxed short with graphic print in light blue",
        brand:"ASOS DESIGN",
        type:"Shorts",
        price:24.00,
    }
]

const cont=document.getElementById("cont");

display(prod)
function display(data){
    cont.innerHTML=null;
    data.forEach((elem)=>{
        const card=document.createElement("div");
        const img=document.createElement("img");
        const brand=document.createElement("h3");
        const price=document.createElement("h4")
        const title=document.createElement("p")
        const cat=document.createElement("p")
        const Add=document.createElement("button")

        img.src=elem.img;
        brand.innerText=elem.brand;
        price.innerText=`$ ${elem.price}`;
        title.innerText=elem.title;
        cat.innerText=elem.type;
        Add.innerText="Add to Cart"

        card.append(img,brand,price,title,cat,Add);
        cont.append(card);
    })
}

